### ISSUE TITLE
panic: Modify not implemented for node type <nil>

### ISSUE THREAD

**Issue by ldemailly** [grol-io/grol#227]
```
panic: Modify not implemented for node type <nil>
goroutine 82 [running]:
grol.io/grol/ast.Modify({0x0?, 0x0?}, 0x14000598ec8?)
	/Users/dl/dev/grol-io/grol/ast/modify.go:119 +0xe2c
grol.io/grol/ast.Modify({0x100a9e518?, 0x1400000fe00}, 0x14000598ec8)
	/Users/dl/dev/grol-io/grol/ast/modify.go:44 +0x340
grol.io/grol/ast.Modify({0x100a9d518?, 0x1400040b6e0}, 0x14000598ec8)
	/Users/dl/dev/grol-io/grol/ast/modify.go:12 +0x1518
grol.io/grol/ast.Modify({0x100a9e4c8?, 0x140002ed530}, 0x14000598ec8)
	/Users/dl/dev/grol-io/grol/ast/modify.go:32 +0xec
grol.io/grol/ast.Modify({0x100a9d518?, 0x1400040b660}, 0x14000598ec8)
	/Users/dl/dev/grol-io/grol/ast/modify.go:12 +0x1518
grol.io/grol/ast.Modify({0x100a9e540?, 0x140006119c0}, 0x14000598ec8)
	/Users/dl/dev/grol-io/grol/ast/modify.go:52 +0x1124
grol.io/grol/ast.Modify({0x100a9e590?, 0x140002ec900}, 0x14000598ec8)
	/Users/dl/dev/grol-io/grol/ast/modify.go:69 +0x13fc
grol.io/grol/ast.Modify({0x100a9d4c8?, 0x140002ec8d0}, 0x14000598ec8)
	/Users/dl/dev/grol-io/grol/ast/modify.go:18 +0x438
grol.io/grol/ast.Modify({0x100a9d518?, 0x1400040b540}, 0x14000598ec8)
	/Users/dl/dev/grol-io/grol/ast/modify.go:12 +0x1518
grol.io/grol/eval.(*State).ExpandMacros(...)
	/Users/dl/dev/grol-io/grol/eval/macro_expension.go:77
grol.io/grol/eval.EvalString({0x100a8d4a0, 0x14000151830}, {0x140005ca000?, 0x100dbe110?}, 0x0)
	/Users/dl/dev/grol-io/grol/eval/eval_api.go:192 +0x2c4
grol.io/grol/repl.AutoLoad(0x14000151830, {0x0, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, {0x0, ...}, ...})
	/Users/dl/dev/grol-io/grol/repl/repl.go:94 +0x220
grol.io/grol/repl.EvalStringWithOption({0x100a9f448, 0x100e3b920}, {0x0, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/Users/dl/dev/grol-io/grol/repl/repl.go:185 +0xd4
main.evalInput({0x140002ce080?, 0x3c400000000001?}, 0x14000599708)
	/Users/dl/dev/grol-io/grol-discord-bot/bot.go:313 +0x544
```

Somehow not triggered through grol tests but only discord bot - need to add a test that uses the same

repl.EvalStringWithOption with same options

**Comment by ldemailly** [comment]
call is
```go
		evalres, errs, formatted := repl.EvalStringWithOption(context.Background(), cfg, input)
```
with
```go
		cfg := replConfig()
		cfg.Compact = p.compactMode
		cfg.AllParens = p.debugParenMode
		cfg.PreInput = func(state *eval.State) {
			st := MessageState{
				Session:          p.session,
				ChannelID:        p.channelID,
				TriggerMessageID: p.message.ID,
				ImageMap:         state.Extensions["image.new"].ClientData.(extensions.ImageMap),
			}
			name, fn := ChannelMessageSendComplexFunction(&st)
			state.Extensions[name] = fn
			name, fn = SendImageFunction(&st)
			state.Extensions[name] = fn
		}
```
and
```go
func replConfig() repl.Options {
	cfg := repl.EvalStringOptions()
	cfg.AutoLoad = true
	cfg.AutoSave = AutoSave
	cfg.MaxDepth = *depth
	cfg.MaxValueLen = *maxLen
	cfg.PanicOk = *panicF
	cfg.MaxDuration = *maxDur
	return cfg
}
```
